// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnAXfpuXwfLSWKkF1rInRCjiQB54GnIkg',
    appId: '1:1074161513774:web:1b22b81a2cf8f2618736bf',
    messagingSenderId: '1074161513774',
    projectId: 'tasks-man-25',
    authDomain: 'tasks-man-25.firebaseapp.com',
    storageBucket: 'tasks-man-25.firebasestorage.app',
    measurementId: 'G-B5X1EGEBPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCDptL7VxTkSxJmHquO1N7N84OE86IUKI',
    appId: '1:1074161513774:android:f1cf17afc951dce28736bf',
    messagingSenderId: '1074161513774',
    projectId: 'tasks-man-25',
    storageBucket: 'tasks-man-25.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnAXfpuXwfLSWKkF1rInRCjiQB54GnIkg',
    appId: '1:1074161513774:web:527c65fb564ab74e8736bf',
    messagingSenderId: '1074161513774',
    projectId: 'tasks-man-25',
    authDomain: 'tasks-man-25.firebaseapp.com',
    storageBucket: 'tasks-man-25.firebasestorage.app',
    measurementId: 'G-35EK0EP5Q0',
  );
}
